<a href="https://colab.research.google.com/github/mahveen1506/Machine-Learning/blob/main/KNN_Classifier_IRIS_Flowers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**VIDYA JYOTHI INSTITUTE OF TECHNOLOGY**
**Name: Mahveen Fatima**
**Roll No: 24911A6697**
**Branch: CSE(AI-ML)**

W8 Classification of IRIS Flower Dataset using KNN Clasifier

In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [62]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [63]:
df=pd.read_csv('/content/drive/MyDrive/iris.csv')

In [64]:
print(df.shape)

(150, 5)

In [65]:
print(df.head)

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [66]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [67]:
print(df.species)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [69]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
le.fit(df.species)
df['species']=le.transform(df.species)
print(df)

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [70]:
print(df.species)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [71]:
x=df.iloc[:,:4]

In [72]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [73]:
y=df.iloc[:,4]

In [74]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [75]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.70,random_state=42)

In [76]:
print(x_train.shape)

(105, 4)

In [77]:
print(x_test.shape)

(45, 4)

In [78]:
print(y_train.shape)

(105,)

In [79]:
print(y_test.shape)

(45,)

In [80]:
x_train

     sepal_length  sepal_width  petal_length  petal_width
81            5.5          2.4           3.7          1.0
133           6.3          2.8           5.1          1.5
137           6.4          3.1           5.5          1.8
75            6.6          3.0           4.4          1.4
109           7.2          3.6           6.1          2.5
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[105 rows x 4 columns]

In [81]:
y_train

81     1
133    2
137    2
75     1
109    2
      ..
71     1
106    2
14     0
92     1
102    2
Name: species, Length: 105, dtype: int64

In [82]:
model=KNeighborsClassifier(n_neighbors=5)

In [83]:
model

KNeighborsClassifier()

In [84]:
model_train=model.fit(x_train,y_train)

In [85]:
model_train

KNeighborsClassifier()

In [86]:
y_pred=model_train.predict(x_test)

In [87]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [88]:
y_pred[0:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1])

In [89]:
print(y_test[:10])

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
Name: species, dtype: int64

In [90]:
i=0
print("\n-------------------------------------------------")
print('%-25s %-25s %-25s' % ('Original Label', 'Predicted Label', 'Correct/Wrong'))
print("--------------------------------------------------")
for label in y_test:
  print('%-25s %-25s' % (label, y_pred[i]), end="")
  if(label==y_pred[i]):
    print('%-25s' % ('Correct'))
  else:
    print('%-25s' % ('Wrong'))
  i=i+1
print("--------------------------------------------------")

-------------------------------------------------
Original Label            Predicted Label           Correct/Wrong
--------------------------------------------------
1                         1                        Correct
0                         0                        Correct
2                         2                        Correct
1                         1                        Correct
1                         1                        Correct
0                         0                        Correct
1                         1                        Correct
2                         2                        Correct
1                         1                        Correct
1                         1                        Correct
2                         2                        Correct
0                         0                        Correct
0                         0                        Correct
0                         0                        Correct
0                         0                        Correct
1                         1                        Correct
2                         2                        Correct
1                         1                        Correct
1                         1                        Correct
2                         2                        Correct
0                         0                        Correct
2                         2                        Correct
0                         0                        Correct
2                         2                        Correct
2                         2                        Correct
2                         2                        Correct
2                         2                        Correct
2                         2                        Correct
0                         0                        Correct
0                         0                        Correct
0                         0                        Correct
0                         0                        Correct
1                         1                        Correct
0                         0                        Correct
0                         0                        Correct
2                         2                        Correct
1                         1                        Correct
0                         0                        Correct
0                         0                        Correct
0                         0                        Correct
2                         2                        Correct
1                         1                        Correct
1                         1                        Correct
0                         0                        Correct
0                         0                        Correct
--------------------------------------------------

In [91]:
import sklearn.metrics as metrics
confusion=metrics.confusion_matrix(y_test,y_pred)
confusion

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [92]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

1.0

In [93]:
print('Accuracy of the classifier is %0.2f' % metrics.accuracy_score(y_test,y_pred))
print(" --------------------------------------------------------------------------")

Accuracy of the classifier is 1.00
 --------------------------------------------------------------------------

In [94]:
print("\nClassification Report:\n",)
class_wise=metrics.classification_report(y_test,y_test)
print(class_wise)

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

In [95]:
new_sample=[[5.1,3.5,1.4,0.2]]
prediction=model.predict(new_sample)
predicted_label=le.inverse_transform(prediction)
print("Predicted Class:",predicted_label)

Predicted Class: ['setosa']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(